[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
anchor_counter = "4X3wohHowHuh1rcV9Pjay2nTNhkdcVJGYT6eoYuUL9LC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/home/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
