[toolchain]

[features]
seeds = true
skip-lint = false

[programs.devnet]
anchor_counter = "9sqmxJ8CAKANCGzv3cXH3D2UnKh9e9DPiSoDsq5EwUo9"

[programs.localnet]
anchor_counter = "9sqmxJ8CAKANCGzv3cXH3D2UnKh9e9DPiSoDsq5EwUo9"

[programs.mainnet]
anchor_counter = "9sqmxJ8CAKANCGzv3cXH3D2UnKh9e9DPiSoDsq5EwUo9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
