import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { headers } from 'next/headers';
import { cookieToInitialState } from 'wagmi';

import { config } from '@/app/config';
import { CounterContextProvider } from '@/app/context/CounterContextProvider';
import { ParentWalletContextProvider } from '@/app/context/WalletContextProvider';
import { Web3ModalProvider } from '@/app/context/Web3ModalProvider';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get('cookie'));

  return (
    <html lang='en'>
      <body className={inter.className}>
        <Web3ModalProvider initialState={initialState}>
          <ParentWalletContextProvider>
            <CounterContextProvider>{children}</CounterContextProvider>
          </ParentWalletContextProvider>
        </Web3ModalProvider>
      </body>
    </html>
  );
}
